name: dropdown_picker
description: Dropdown picker for local and remote data, single and multi select.
version: 0.0.2
repository: https://github.com/salihagic/dropdown_picker

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
